### ISSUE TITLE
Just a query not an issue

### ISSUE THREAD

**Issue by vishnucool220** [wearyinside/qmlcreator#1]
you have defined stackView in main.qml
how you are able to access this in ExamplesScreen.qml ? and all other files.Thanks
 P.S: I am new to qml

**Comment by olegyadrov** [comment]
Since StackView declared in the "root" component, it is available by id from any other component. You can read more about scope and naming resolution in QML [here](http://doc.qt.io/qt-5/qtqml-documents-scope.html). Also, I would recommend you to read the documentation of [StackView](http://doc.qt.io/qt-5/qml-qtquick-controls-stackview.html) item.

**Comment by vishnucool220** [comment]
Thanks

**Comment by vishnucool220** [comment]
I have read through the documents and i have implemented in the same way as you did. But when i pop and again push the same qml page. The states of the Buttons(on/off) are not maintained. I think because when i am pushing I am not making destroyOnPop to false.May i know how to maintain the staus of buttons.
I did like this. 
Button{
            id:openDetailedview
            text:"Detailed View"
            onClicked: {
                stackView.push(Qt.resolvedUrl("DetailedView.qml"))
            }
        }
In DetailedView.qml there are many on/off buttons.Also, It says that qml: Warning: StackView: cannot transition an item that is anchored!.May i know when do we get this kind of error because i even set anchors.fill:parent. Thanks.

**Comment by vishnucool220** [comment]
hi, 
I did like this 
Button{
            id:openDetailedview
            text:"Detailed View"
            onClicked: {
                stackView.push({item:detailedView,destroyOnPop:false})
            }
        }
DetailedView{
        id:detailedView
        visible: false
    }
...
The only problem is qml: Warning: StackView: cannot transition an item that is anchored!. I didn't anchor it but still it says that.any help please ?
