### ISSUE TITLE
Failing compilation with CLANG on Mac OS X 10.10

### ISSUE THREAD

**Issue by ThomasVogelpohl** [wearyinside/qmlcreator#2]
Hi Oleg,

I can not compile qmlcreator with CLANG. 
CLANG does not enable the C++11 extensions with the current project config.
I had to change in qmlcreator.pro:
# QMAKE_CXXFLAGS += -std=c++11

CONFIG += c++11

and now it compiles and runs OK.

Nice software anyway !!

Best regards,
Thomas

**Comment by olegyadrov** [comment]
Hi Thomas,

Thank you for the feedback. In the last commit [b69368b](https://github.com/wearyinside/qmlcreator/commit/b69368b1987d8567844861aab155c7fe51bb032e) I have removed the -std=c++11 flag and cleaned the syntax highlighting code, so it should be compilable out-of-box now.

Thank you,
Oleg
